[project]
name = "day5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Suryashekhar Dutta", email = "suryashekhardutta@example.com" }
]
requires-python = ">=3.11"
dependencies = [
    "groq>=1.7.0",
    "pypdf>=6.19.0",
    "pydantic>=2.0.0",
    "python-docx>=1.1.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
day5 = "day5:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
